config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :lists
    resources :list_items
    root to: "users#index"
  end

  devise_for :users
  root 'home#index'
  get 'contact' => 'home#contact'

  namespace :api do
    resources :static, only: [:index]
    resources :lists, only: [:index, :show, :create, :update]
    resources :list_items, only: [:create] do
      collection do
        post :add_to_basket
      end
    end
  end

  resources :lists do
    member do
      get :copy
      resource :list_items do
        member do
          get :add_to_basket
        end
      end
    end
  end

end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_lists_on_user_id  (user_id)
#

class List < ActiveRecord::Base
  belongs_to :user
  has_many  :list_items, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: { scope: :user_id }
  before_save :downcase_name

  scope :search, -> (query) {
    where('lists.name like ?', "%#{query.try(:downcase) || ''}%")
  }

  scope :for_user, -> (name) {
    joins(:user).where('users.name = ?', name.downcase)
  }

  scope :not_for_user, -> (name) do
    joins(:user).where('users.name != ?', name.downcase)
  end

  private
  def downcase_name
    self.name = name.downcase
  end
end

app/models/list/list_creator.rb
class List
  class ListCreator
    attr_reader :list

    def initialize(list)
      @list = list
    end

    def run
      user = User.find_by(email: default_email)

      new_list = user.lists.create!(name: list.name)
      create_list_items(new_list)

      creator_response(new_list)
    end

    private
    def default_email
      "james@foggy.io"
    end

    def create_list_items(new_list)
      list.list_items.each do |old_list_item|
        new_list.list_items.create!(name: old_list_item.name)
      end
    end

    def creator_response(new_list)
      {
        text: text_response(new_list),
        status: "CREATED",
        id: new_list.id
      }
    end

    def text_response(new_list)
      "".tap do |response|
        response << "I've created a list for #{new_list.name}. "
        response << "The list contains #{new_list.list_items.map(&:name)}"
      end
    end
  end
end

app/models/list/response_maker.rb
class List
  class ResponseMaker
    attr_reader :query

    STATUSES = {
      found: 'FOUND',
      recommended: 'RECOMMENDED',
      found_friend: 'FOUND_FRIEND',
      created: 'CREATED',
      not_found: 'NOT_FOUND',
      show_found: 'SHOW_FOUND'
    }.freeze

    def initialize(query)
      @query = query
    end

    def run
      if run_query.any?
        found_response
      elsif recommend_for_query.any?
        recommended_response
      else
        none_response
      end
    end

    def show(list)
      show_response(list)
    end

    private

    def run_query
      List.for_user(default_user).search(query)
    end

    def recommend_for_query
      List.not_for_user(default_user).search(query)
    end

    def default_user
      'james'
    end

    def found_response
      {
        text: Response.list_found_text(run_query),
        status: STATUSES[:found],
        id: run_query.first.id
      }
    end

    def recommended_response
      {
        text: Response.recommended_text(query, recommend_for_query),
        status: STATUSES[:recommended],
        id: recommend_for_query.first.id
      }
    end

    def none_response
      {
        text: Response.none_text(query),
        status: STATUSES[:not_found]
      }
    end

    def show_response(list)
      {
        text: Response.show_text(list),
        status: STATUSES[:show_found],
        id: list.id
      }
    end
  end
end

app/controllers/admin/lists_controller.rb
module Admin
  class ListsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = List.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   List.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApiController
  skip_before_filter :verify_authenticity_token
  def index
    respond_to do |format|
      format.json { render json: List::ResponseMaker.new(params[:q]).run }
    end
  end

  def show
    list = List.find params[:id]
    respond_to do |format|
      format.json { render json: List::ResponseMaker.new(params[:q]).show(list)}
    end
  end

  def create
    user = User.find_by(email: "james@foggy.io")
    list = List.create(name: params[:list_name], user: user)
    if list.valid?
      response = create_response(list)
    else
      response = {
        text: "You aready have a #{params[:list_name]} list for James.",
        status: "LIST_EXISTS",
        id: List.find_by(name: params[:list_name])
      }
    end
    respond_to do |format|
      format.json { render json: response }
    end
  end

  def update
    @list = List.find params[:id]

    respond_to do |format|
      format.json { render json: List::ListCreator.new(@list).run }
    end
  end

  private
  def create_response(list)
    {
      text: Response.list_create_text(list),
      status: 'CREATED_LIST',
      id: list.id
    }
  end
end

app/controllers/lists_controller.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_lists_on_user_id  (user_id)
#

class ListsController < ApplicationController
  enable_sync only: [:create, :update, :destroy]
  before_action :authenticate_user!

  def index
    if params[:q]
      search_param = "%#{params[:q]}%"
      @lists = List
        .where("name like ?", search_param).all.order(:user_id).order(created_at: :desc)
      @list_item = ListItem.new
      respond_to do |format|
        format.html
      end

    else
      @lists = current_user.lists.order(:user_id).order(created_at: :desc)
      @list_item = ListItem.new
    end
    
  end

  def show
    @list = List.find(params[:id])
    @list_item = ListItem.new
  end

  def new
    @list = List.new
  end

  def destroy
    debugger
    @list.destroy
    redirect_to request.referrer || root_url
  end

  def create
    @list = current_user.lists.create(list_params)
    @list_items = @list_items
    if @list.save
      redirect_to @list
    else
      render 'new'
    end
  end

  def copy
    current_list = List.find(params[:id])
    @list = current_list.dup
    @list.update_attributes!(user: current_user)
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/views/lists/_list.html.erb
<li id="list-<%= list.id %>">
  <div class="col s6">
    <% if list.user == current_user %>
      <div class="card green lighten-5">
    <%else %>
      <div class="card red lighten-5">
      <%end %>
      <div class="card-content">
        <div class="card-title">
          <span><%= list.name %></span>
          <span class="right"><%= list.user.try(:name) || list.user.try(:email) %></span>
        </div>
        <ul class="collection" >
          <%= render list.list_items %>
        </ul>
        <div class="card-action">
          <%= link_to 'View', list, class: "btn waves-effect waves-light" %>
          <button data-target="add_item" class="btn modal-trigger">Add Item</button>
          <% if current_user != list.user %>
            <%= link_to 'Copy', copy_list_path(list), class: "btn waves-effect waves-light" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>
<!-- Modal Structure -->
<div id="add_item" class="modal">
  <div class="modal-content">
    <h4>Add an Item</h4>
    <%= form_for(@list_item, url: new_list_items_path(list), html: { multipart: true}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class='field'>
        <%= f.text_field :name, placeholder: 'Add new item...', autofocus: true%>
      </div>
      <div class="modal-footer">
        <%= f.submit 'Add',  class: "modal-action modal-close waves-effect waves-green btn-flat " %>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
</script>

app/views/lists/index.html.erb
<script>
  $(document).on('ready page:load', function() {
    if (window.location.pathname !== '/lists') {
      return false;
    }
    console.log('refresh')
      var REFRESH_INTERVAL_IN_MILLIS = 2000;
      setTimeout(function(){
        Turbolinks.enableTransitionCache(true);
        Turbolinks.visit(location.toString());
        Turbolinks.enableTransitionCache(false);
      }, REFRESH_INTERVAL_IN_MILLIS);
  });
// window.setInterval(function(){
//   window.location.reload();
// }, 1000);
</script>
<ul class="lists">
  <div class="row">
  <% @lists.each do |list| %>
    <%= render list %>
  <% end %>
  </div>
</ul>

app/views/lists/new.html.erb
<div class="container">
  <h2 class="row center">New list</h2>
  <div class="card">
    <div class="row">
      <div class="col s6 offset-s3">
        <%= form_for(@list) do |f| %>
          <div class="row">
            <div class="input-field">
              <%= f.label :name ,class: "validate" %><br />
              <%= f.text_field :name, autofocus: true %>
            </div>
          </div>
          <div class="card-action center">
            <button class="btn waves-effect waves-light">
              <%= f.submit "Create list" do %>
              <i class="material-icons right">plus</i>
              <% end %>
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
  <div class="container">
    <h2 class="row center card-title"><%= @list.name %></h2>
    <div class="row">
      <div class="col s12">
        <div class="card">
          <div class="card-content">
            <ul class="collection" >
              <%= render @list.list_items %>
            </ul>
            <div class="card-action">
              <button data-target="add_item" class="btn modal-trigger">Add Item</button>
              
             </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</li>
<!-- Modal Structure -->
<div id="add_item" class="modal">
  <div class="modal-content">
    <h4>Add an Item</h4>
    <%= form_for(@list_item, html: { multipart: true}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class='field'>
        <%= f.text_field :name, placeholder: 'Add new item...', autofocus: true %>
      </div>
      <div class="modal-footer">
        <%= f.submit 'Add',  class: "modal-action modal-close waves-effect waves-green btn-flat " %>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
</script>