config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :lists
    resources :list_items
    root to: "users#index"
  end

  devise_for :users
  root 'home#index'
  get 'contact' => 'home#contact'

  namespace :api do
    resources :static, only: [:index]
    resources :lists, only: [:index, :show, :create, :update]
    resources :list_items, only: [:create] do
      collection do
        post :add_to_basket
      end
    end
  end

  resources :lists do
    member do
      get :copy
      resource :list_items do
        member do
          get :add_to_basket
        end
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:contact]

  def index
    @list = List.new
  end

  def contact
  end
end

app/views/home/contact.html.erb
This should be be visible to signed up users

app/views/home/index.html.erb
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center  green-text">Foggy</h1>
      <div class="row center">
        <h5 class="header col s12 light">Worrying about the little things for you</h5>
      </div>
      <div class="row center">
        <% if user_signed_in? %>
          Hi <%= current_user.email %>
          <div class="container">
            <div class="search-bar col s12">
              <%= form_tag(lists_path, method: :get) do %>
                <%= text_field_tag(:q, params[:q], class: "form-control", placeholder: "search..") %>
              <% end %>
            </div>
          </div>
          <section>
          <%= link_to "Create a new list", new_list_path, class: "btn-large waves-effect waves-light green" %>
          <%= link_to "View lists", lists_path, class: "btn-large waves-effect waves-light green" %>
          </section>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "btn-large waves-effect waves-light green" %>
        <% end %>
      </div>
      <br><br>

    </div>
  </div>

  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Never forget the little things again</h5>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Crowdsource a list</h5>

            
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Focus on the imporant things</h5>

            
          </div>
        </div>
      </div>

    </div>
    <br><br>

    <div class="section">

    </div>
  </div>
<script>
  init: function() {
    var things_to_do = ['go to the gym', 'cook a healthy meal', 'improve myself',
                        'run a mile a day', 'write some code', 'quit smoking',
                        'write a blog', 'build my confidence', 'do a good deed'];
    typeout('.challenge_search_text', things_to_do, {numLoops: 10, interval: 1000});
  }
</script>