config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :lists
    resources :list_items
    root to: "users#index"
  end

  devise_for :users
  root 'home#index'
  get 'contact' => 'home#contact'

  namespace :api do
    resources :static, only: [:index]
    resources :lists, only: [:index, :show, :create, :update]
    resources :list_items, only: [:create] do
      collection do
        post :add_to_basket
      end
    end
  end

  resources :lists do
    member do
      get :copy
      resource :list_items do
        member do
          get :add_to_basket
        end
      end
    end
  end

end

app/views/layouts/_footer.html.erb
<!-- <footer class="page-footer blue darken-4">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Motivation</h5>
          <p class="grey-text text-lighten-4">This bootstrap project was created to help developers start developing a Minimum Viable Product in not time.</p>

        </div>
        <div class="col l3 s12">
          <h5><%= link_to 'Contact', contact_path ,class: "white-text"%></h5>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        Published by <a class="orange-text text-lighten-3" href="https://github.com/faethonm">Faethon Milikouris</a>
      </div>
    </div>
  </footer>
 -->

app/views/layouts/_header.html.erb
<header >
  <nav class="green" role="navigation">
    <div class="nav-wrapper container">
      <%= link_to "Foggy", root_url, id: "logo", class: "brand-logo", id: "logo-container"  %>
      <ul class="right hide-on-med-and-down">
         <li><%= link_to "Home",   root_url %></li>

         <% if user_signed_in? %>
         <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete%></li>
         <li><%= link_to "Contact Us",   contact_url %></li>
         <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>
      </ul>

      <ul id="nav-mobile" class="side-nav">
         <li><%= link_to "Home",   root_url %></li>

         <% if user_signed_in? %>
         <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete%></li>
         <li><%= link_to "Contact Us",   contact_url %></li>
         <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= include_sync_config %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="container">
        <%= yield %>
      
      </div>

    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>